networks:
  traefik:
    external: true
    name: traefik

services:
  no-pressure:
    container_name: no-pressure
    image: no-pressure:local
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.no-pressure.loadbalancer.server.port=80"
      - "traefik.http.routers.no-pressure-secure.rule=Host(`nopressure.${DOMAIN}`)"
      - "traefik.http.routers.no-pressure-secure.entrypoints=websecure"
      - "traefik.http.routers.no-pressure-secure.tls.certresolver=le"
      - "traefik.http.routers.no-pressure-secure.priority=1"
      - "traefik.http.routers.no-pressure-secure.middlewares=restricted-ips@file"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
