name: Deploy No Pressure to VPS

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_TARGET: "/opt/${{ github.event.repository.name }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          source: "."
          target: "${{ env.DEPLOY_TARGET }}"

      - name: Write deploy env file
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_TARGET: ${{ env.DEPLOY_TARGET }}
          DOMAIN: ${{ vars.DOMAIN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          envs: DEPLOY_TARGET,DOMAIN
          script: |
            cd "$DEPLOY_TARGET"
            envsubst < .env.prod.template > .env.prod

      - name: Build and Run service
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_TARGET: ${{ env.DEPLOY_TARGET }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          envs: DEPLOY_TARGET
          script: |
            cd "$DEPLOY_TARGET"
            docker compose -f docker-compose-prod.yml --env-file .env.prod build
            docker compose -f docker-compose-prod.yml --env-file .env.prod up -d
